## Python Introductory Workshop by University of San Diego (USD)  
### Part 1
**Leonid Shpaner**  
**January 21, 2022**

Whereas JupyterLab and Jupyter Notebook are the two most commonly used interactive computing platforms warehoused within the Anaconda distribution, data scientists can also leverage the cloud-based coding environment of Google Colab.

[https://colab.research.google.com/?utm_source=scs-index](https://colab.research.google.com/?utm_source=scs-index)


## JupyterLab Basics
[https://jupyterlab.readthedocs.io/en/stable/user/interface.html](https://jupyterlab.readthedocs.io/en/stable/user/interface.html)

## Cells

In [2]:
# This is a code cell/block!

# basic for loop
for x in [1,2,3,4,5,6]:
    print(x)


1
2
3
4
5
6


This is a markdown cell!  
#### Level 3 Heading  
*italics characters are surrounded by one asterisk*  
**bold characters are surrounded by two asterisks**  
* one asterisk in front of an item of text can serve as a bullet point.  
* to move the text to the next line, ensure to enter two spaces after the line.   
    1. Simply number the items on a list using normal numering schema.  
    2. If you have numbers in the same markdown cell as bullet points (i.e., below),
    3. skip 4 spaces after the last bullet point and then begin numbering.

Here's a guide for syntax: https://www.markdownguide.org/basic-syntax/

## Python Basics

We can use a code cell to conduct basic math operations as follows.

In [3]:
2+2

4

Order of operations in Python is just as important.

In [4]:
1+3*10 == (1+3)*10

False

For more basic operations including but not limited to taking the square root, log, and generally more advanced mathematical operations, we will have to import our first library (math) as follows:

In [5]:
import math

However, if we run two consecutive lines below without assigning to a variable or parsing in a print statement ahead of the function calls, only the latest (last) function will print the output of what is in the cell block.

In [6]:
print(math.sqrt(9))
math.log10(100)
math.factorial(10)

3.0


3628800

Let us try this again, by adding `print()` statements in front of the three functions, respectively.

In [7]:
# print the output on multiple lines
print(math.sqrt(9))
print(math.log10(100))
print(math.factorial(10))

3.0
2.0
3628800


## What is a string?

A string is simply any open alpha/alphanumeric text characters surrounded by either single quotation marks or double quotation marks, with no preference assigned for either single or double quotation marks, with a print statement being called prior to the strings. For example,


In [10]:
print('This is a "string".')
print( "This is also a 'string123'.")

This is a "string".
This is also a 'string123'.


Strings in Python are arrays of bytes that represent "Unicode characters" (GeeksforGeeks, 2021).

## Creating Objects

Unlike R, Python uses the '=' symbol for making assignment statements. we can `print()` what is contained in the assignment or just call the assignment to the string as follows:

In [11]:
cheese = 'pepper jack'
cheese 

'pepper jack'

## Determining and Setting the Current Working Directory

The importance of determining and setting the working directory cannot be stressed enough. 
  1. Run `import os` to import operating system module. 
  2. then assign `os.getcwd()` to `cwd`.
  3. You may choose to print the working directory using the print function as shown below.
  4. Or change the working directory by running `os.chdir('')`.


In [12]:
import os # import the operating system module
cwd = os.getcwd()
# Print the current working directory
print("Current working directory: {0}".format(cwd))

# Change the current working directory
# os.chdir('')

# Print the current working directory
print("Current working directory: {0}".format(os.getcwd()))

Current working directory: C:\Users\pqara\OneDrive\Documents\Parastoo\ADS500B\OH_material\module3
Current working directory: C:\Users\pqara\OneDrive\Documents\Parastoo\ADS500B\OH_material\module3


## Installing Libraries

To install most common libraries, simply type in the command `pip install` `followed by library name` into an empty code cell and run it.

In [13]:
# pip install pandas 

## Loading Libraries

For data science applications, we most commonly use [pandas](https://pandas.pydata.org/pandas-docs/stable/) for "data structures and data analysis tools" (Pandas, 2021) and [NumPy](https://numpy.org/) for "scientific computing with Python" (Numpy.org, n.d.). 

Ideally, at the beginning of a project, we will create an empty cell block that loads all of the libraries that we will be using. However, as we progress throughout this tutorial, we will load the necessary libraries separately.

Let us now load these two libraries into an empty code cell block using `import` `name of the library` `as` `abbreviated form`.

In [14]:
import pandas as pd
import numpy as np

Sometimes, `Python` throws warning messages in pink on the output of code cell blocks that otherwise run correctly.  

In [15]:
import warnings
warnings.warn('This is an example warning message.') # displaying warning


C:\Users\pqara\AppData\Local\Temp/ipykernel_3252/3842374809.py:2: UserWarning: This is an example warning message.
  warnings.warn('This is an example warning message.') # displaying warning


Sometimes, it is helpful to see what these warnings are saying as added layers of de-bugging. However, they may also create unsightly output. For this reason, we will suppress any and all warning messages for the remainder of this tutorial.  

To disable/suppress warning messages, let us write the following:


In [16]:
import warnings
warnings.filterwarnings("ignore")

## Data Types

Text Type (string): `str`  
Numeric Types:      `int`, `float`, `complex`  
Sequence Types:	    `list`, `tuple`, `range`  
Mapping Type:	    `dict` - dictionary (used to store key:value pairs)  
Logical:	        `bool` - boolean  (True or False)   
Binary Types:	    `bytes`, `bytearray`, `memoryview`  

Let us convert an integer to a string. We do this using the `str()` function. Recall, how in R, this same function call is designated for something completely different - inspecting the structure of the dataframe.

We can also examine `floats` and `bools` as follows:

In [17]:
# assign the variable to an int
int_numb  = 2356
print('Integer:', int_numb)

# assign the variable to a float
float_number = 2356.0
print('Float:', float_number)

# convert the variable to a string
str_numb = str(int_numb)
print('String:',str_numb)

# convert variable from float to int
int_number = int(float_number)

# boolean
bool1 = 2356 > 235
bool2 = 2356 == 235
print(bool1)
print(bool2)

Integer: 2356
Float: 2356.0
String: 2356
True
False


## Data Structures 

**What is a variable?**
A variable is a container for storing a data value, exhibited as a reference to "to an object in memory which means that whenever a variable is assigned to an instance, it gets mapped to that instance. A variable in R can store a vector, a group of vectors or a combination of many R objects" (GeeksforGeeks, 2020). 

There are 3 most important data structures in Python: vector, matrix, and dataframe.  

**Vector**:  the most basic type of data structure within R; contains a series of values of the same data class. It is a "sequence of data elements" (Thakur, 2018). 

**Matrix**: a 2-dimensional version of a vector. Instead of only having a single row/list of data, we have rows and columns of data of the same data class.

**Dataframe**: the most important data structure for data science. Think of dataframe as loads of vectors pasted together as columns. Columns in a dataframe can be of different data class, but values within the same column must be the same data class.



## Creating Objects

We can make a one-dimensional horizontal list as follows:

In [18]:
list1 = [0, 1, 2, 3]
list1

[0, 1, 2, 3]

or a one-dimensional vertical list as follows:

In [19]:
list2 = [[1],
         [2],
         [3],
         [4]]
list2

[[1], [2], [3], [4]]

## Vectors and Their Operations
Now, to vectorize these lists, we simply assign it to the `np.array()` function call:

In [20]:
vector1 = np.array(list1)
print(vector1)
print('\n') # for printing an empty new line 
            # between outputs
vector2 = np.array(list2)
print(vector2)

[0 1 2 3]


[[1]
 [2]
 [3]
 [4]]


Running the following basic between vector arithmetic operations (addition, subtraction, and division, respectively) changes the resulting data structures from one-dimensional arrays to two-dimensional matrices. 

In [21]:
# adding vector 1 and vector 2
addition = vector1 + vector2

# subtracting vector 1 and vector 2
subtraction = vector1 - vector2

# multiplying vector 1 and vector 2
multiplication = vector1 * vector2

# divifing vector 1 by vector 2
division = vector1 / vector2

# Now let's print the results of these operations
print('Vector Addition: ', '\n', addition, '\n')
print('Vector Subtraction:', '\n', subtraction, '\n')
print('Vector Multiplication:', '\n', multiplication, '\n')
print('Vector Division:', '\n', division)

Vector Addition:  
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]] 

Vector Subtraction: 
 [[-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]
 [-4 -3 -2 -1]] 

Vector Multiplication: 
 [[ 0  1  2  3]
 [ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  4  8 12]] 

Vector Division: 
 [[0.         1.         2.         3.        ]
 [0.         0.5        1.         1.5       ]
 [0.         0.33333333 0.66666667 1.        ]
 [0.         0.25       0.5        0.75      ]]


Similarly, a vector of logical strings will contain

In [22]:
vector3 = np.array([True, False, True, False, True])
vector3

array([ True, False,  True, False,  True])

Whereas in R, we use the `length()` function to measure the length of an object (i.e., vector, variable, or dataframe), we apply the `len()` function in `Python` to determine the number of members inside this object.

In [23]:
len(vector3)

5

Let us say for example, that we want to access the third element of `vector1` from what we defined above. In this case, the syntax is the same as in R. We can do so as follows:

In [25]:
vector1 = [4,5,6,7]
print(vector1)

vector1[3]
vector1[1:3]


[4, 5, 6, 7]


[5, 6]

Let us now say we want to access the first, fifth, and ninth elements of this dataframe. To this end, we do the following:

In [26]:
vector4 = np.array([1,3,5,7,9,20,2,8,10,35,76,89,207])
vector4_index = vector4[1], vector4[5], vector4[9]
vector4_index


(3, 20, 35)

What if we wish to access the third element on the first row of this matrix?

In [27]:
# create (define) new matrix
matrix1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(matrix1)

print('\n','3rd element on 1st row:', matrix1[0,2])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 3rd element on 1st row: 3


## Counting Numbers and Accessing Elements in Python

Whereas it would make sense to start counting items in an array with the number `1` like we do in R, this is not true in Python. We `ALWAYS` start counting items with the number `0` as the first number of any given array in Python.

What if we want to access certain elements within the dataframe? For example:

In [28]:
# find the length of vector 1
print(vector1)
print(len(vector1))

# get all elements
print(vector1[0:4])

# get all elements except last one
print(vector1[0:3])

[4, 5, 6, 7]
4
[4, 5, 6, 7]
[4, 5, 6]
